### ISSUE TITLE
Lista de componentes para montagem de Bina

### ISSUE THREAD

**Issue by presttec** [ArduinoMinas/KIT-Arduino-DTMF-Telefonica#2]
Pode me passar a lista de componentes.
Vi que você tem um shield de bina.
Desejo comprar ela tamb[em

**Comment by carlosdelfino** [comment]
@presttec vou te passar estes videos que é relativo ao projeto: https://www.youtube.com/watch?v=O04S1Aj47RM&list=PLiYirjybg37GmcWebk3XcZkwIYUY3JUar

Não estou achando os arquivos localmente, mas assim que eu encontrar coloco aqui no GitHub, mas desconfio que estão perdidos, só restou os videos acima.

É um projeto muito antigo que está parado a mais de 5 anos.

**Comment by carlosdelfino** [comment]
relativo a Issue #1

**Comment by presttec** [comment]
Eu estou procurando esta solução a 3 anos. 
Imagina minha alegria quando achei este post.

**Comment by carlosdelfino** [comment]
@presttec fico feliz por estar lhe ajudando.

Infelizmente não consegui achar a lista de componentes, eu tive um problema no HD a alguns anos e perdi muitos projetos, e era exatamente o HD de backup do meu MAC que também está queimado.

Achei alguns circuitos que usei como exemplos propostos para o workshop e estão neste link: https://github.com/ArduinoMinas/KIT-Arduino-DTMF-Telefonica/upload/master/images

**Comment by carlosdelfino** [comment]
Eu consegui recuperar o HD que estava com o Backup do projeto, e lembrei que este repositório deveria estar desativado, o original se encontra em https://github.com/ArduinoMinas/SmartBina-CallerID/

**Comment by carlosdelfino** [comment]
@presttec por favor, caso deseje mais informações use o projeto ArduinoMinas/SmartBina-CallerID.
